# SwiftLint configuration for SwiftUMLBridge
#
# identifier_name for Color.swift is suppressed inline because the enum cases
# must use PascalCase to match PlantUML HTML color name strings exactly.
# identifier_name for Theme.swift is suppressed inline because the __directive__
# case is an internal implementation detail that intentionally uses underscores.

excluded:
  - .build

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80
  allowed_symbols: ["_"]
